require('paq-nvim') {
  'folke/twilight.nvim',
  'folke/which-key.nvim',
  'folke/zen-mode.nvim',
  'godlygeek/tabular',
  'hrsh7th/nvim-compe',
  'hrsh7th/vim-vsnip',
  'hrsh7th/vim-vsnip-integ',
  'jubnzv/virtual-types.nvim',
  'kyazdani42/nvim-web-devicons',
  'lewis6991/gitsigns.nvim',
  'mbbill/undotree',
  'mfussenegger/nvim-dap',
  'morhetz/gruvbox',
  'neovim/nvim-lspconfig',
  'nvim-lua/plenary.nvim',
  'nvim-lua/popup.nvim',
  'nvim-telescope/telescope-fzy-native.nvim',
  'nvim-telescope/telescope.nvim',
{ 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' },
  'onsails/lspkind-nvim',
  'savq/paq-nvim',
  'sheerun/vim-polyglot',
  'skanehira/translate.vim',
  'tamago324/lir.nvim',
  'terrortylor/nvim-comment',
  'tpope/vim-surround',
  'vim-pandoc/vim-pandoc-syntax',
  -- 'Th3Whit3Wolf/spacebuddy',
  -- 'ericjuma/neowal',
  -- 'glepnir/lspsaga.nvim',
  -- 'honza/vim-snippets',
  -- 'humanoid-colors/vim-humanoid-colorscheme',
  -- 'junegunn/goyo.vim',
  -- 'junegunn/limelight.vim',
  -- 'justinmk/vim-dirvish',
  -- 'kana/vim-textobj-user',
  -- 'kevinhwang91/rnvimr',
  -- 'kovetskiy/sxhkd-vim',
  -- 'lambdalisue/fern-hijack.vim',
  -- 'lambdalisue/fern.vim',
  -- 'mattn/emmet-vim',
  -- 'nvim-lua/completion-nvim',
  -- 'preservim/nerdtree',
  -- 'rhysd/clever-f.vim',
  -- 'ryanoasis/vim-devicons',
  -- 'saihoooooooo/vim-textobj-space',
  -- 'sirver/ultisnips',
  -- 'tjdevries/colorbuddy.nvim',
  -- 'tomtom/tcomment_vim',
  -- 'wbthomason/packer.nvim',
  -- 'windwp/nvim-autopairs',
  -- 'yamatsum/nvim-nonicons',
}
