# Shell variables
# Generated by 'wal'
wallpaper='/home/gabe/Pictures/wals/gems/phil.jpg'

# Special
background='#211e18'
foreground='#c7c6c5'
cursor='#c7c6c5'

# Colors
color0='#211e18'
color1='#a6977b'
color2='#61ba96'
color3='#a1c2bb'
color4='#7fa7a2'
color5='#5875ab'
color6='#ab393d'
color7='#c7c6c5'
color8='#585651'
color9='#a6977b'
color10='#61ba96'
color11='#a1c2bb'
color12='#7fa7a2'
color13='#5875ab'
color14='#ab393d'
color15='#c7c6c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
