# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#000000'
foreground='#ffffff'
cursor='#da4375'

# Colors
color0='#2a1d17'
color1='#da1657'
color2='#3ea250'
color3='#e3d33d'
color4='#3ea290'
color5='#ff850d'
color6='#8c16da'
color7='#e9e9e9'
color8='#4f362b'
color9='#da1657'
color10='#3ea250'
color11='#e3d33d'
color12='#3ea290'
color13='#ff850d'
color14='#8c16da'
color15='#e9e9e9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
