--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#151515"
foreground="#d0d0d0"
cursor="#d0d0d0"

-- Colors
color0="#151515"
color1="#fb9fb1"
color2="#acc267"
color3="#ddb26f"
color4="#6fc2ef"
color5="#e1a3ee"
color6="#12cfc0"
color7="#d0d0d0"
color8="#505050"
color9="#fb9fb1"
color10="#acc267"
color11="#ddb26f"
color12="#6fc2ef"
color13="#e1a3ee"
color14="#12cfc0"
color15="#f5f5f5"
