# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#151515'
foreground='#d0d0d0'
cursor='#d0d0d0'

# Colors
color0='#151515'
color1='#fb9fb1'
color2='#acc267'
color3='#ddb26f'
color4='#6fc2ef'
color5='#e1a3ee'
color6='#12cfc0'
color7='#d0d0d0'
color8='#505050'
color9='#fb9fb1'
color10='#acc267'
color11='#ddb26f'
color12='#6fc2ef'
color13='#e1a3ee'
color14='#12cfc0'
color15='#f5f5f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
