--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#000000"
foreground="#ffffff"
cursor="#da4375"

-- Colors
color0="#2a1d17"
color1="#da1657"
color2="#3ea250"
color3="#e3d33d"
color4="#3ea290"
color5="#ff850d"
color6="#8c16da"
color7="#e9e9e9"
color8="#4f362b"
color9="#da1657"
color10="#3ea250"
color11="#e3d33d"
color12="#3ea290"
color13="#ff850d"
color14="#8c16da"
color15="#e9e9e9"
