#!/bin/python
from sys import stdin

def rgb2hex(t):
    return '#' + ''.join(tuple(map(
        lambda n: hex(n)[2:].rjust(2, '0')[-2:], t
    )))


def hex2rgb(s):
    return tuple(map(
        lambda n: int(n, 16),
        [s[1:3], s[3:5], s[5:7]]
    ))

print(
    rgb2hex(list(map(
        lambda n: int(n * 0.90),
        hex2rgb(stdin.readline()[:-1])
    )))
)

