#!/bin/bash

if [ "$1" = "rand" ]
then
    color=$(shuf -n 1 ~/.cache/wal/colors)
elif [ "$1" = "bg" ]
then
    source ~/.cache/wal/colors.sh
    color=$background
else
    source ~/.cache/wal/colors.sh
    color=$color8
fi

echo $color

if [ $(theme get mode) = 'dark' ]
then
    color=$(echo $color | colordarken)
else
    color=$(echo $color | colorbrighten)
fi

echo $color

convert -size 100x100 xc:$color jpeg:- | feh --bg-scale - 
