-- vim.cmd('source ~/.config/nvim/packages.vim')
-- vim.cmd('source ~/.config/nvim/utils.vim')
-- vim.cmd('source ~/.config/nvim/settings.vim')
-- vim.cmd('source ~/.config/nvim/keys.vim')
require('packages')
require('settings')
require('autocmds')
require('utils')
require('binds')
require('lspconf')
